stages:
    - build
    - deploy

Build Docker image:
    stage: build
    image: docker
    before_script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.wanadev.org
    script:
        - docker build -t registry.wanadev.org/infra/saltimbanque:$CI_COMMIT_SHA --pull -f ./docker/prod/Dockerfile .
        - docker push registry.wanadev.org/infra/saltimbanque:$CI_COMMIT_SHA
    only:
        - master
        - merge_requests

jast_deploy:
    stage: deploy
    image: node:9
    only:
        - /^v?[0-9]+\.[0-9]+\.[0-9]+(-[a-z0-9]+)?$/
    before_script:
        - npm install -g git+ssh://git@git.wanadev.org:infra/jast.git
    script:
        - jast deploy
