name: "Python Lint"

on: [push, pull_request]

jobs:

  lint:

    name: "Lint"
    runs-on: ubuntu-latest

    steps:

      - name: "Checkout the repository"
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: "Set up Python 3.12"
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: "Install Python dependencies"
        run: |
          pip install setuptools nox

      - name: "Lint with flake8 and Black"
        run: |
          python3 -m nox --session lint
